/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <progress2>
//Requires "progress2" include by Southclaws
//Download: https://github.com/Southclaws/progress2/releases

new PlayerText:HBEBGFOOD[MAX_PLAYERS];
new PlayerText:HBEBGDRINK[MAX_PLAYERS];
new PlayerText:HBEBGFOOD1[MAX_PLAYERS];
new PlayerText:HBEBGDRINK1[MAX_PLAYERS];
new PlayerText:HBEBGMONEY[MAX_PLAYERS];
new PlayerText:HBEBGMONEY1[MAX_PLAYERS];
new PlayerText:HBEMONEY[MAX_PLAYERS];
new PlayerText:HBEFOOD[MAX_PLAYERS];
new PlayerText:HBEDRINK[MAX_PLAYERS];
new PlayerText:HBEMONEYTEXT[MAX_PLAYERS];
new PlayerBar:HBEFOODBAR[MAX_PLAYERS];
new PlayerBar:HBEDRINKBAR[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	HBEBGFOOD[playerid] = CreatePlayerTextDraw(playerid, 594.000000, 395.000000, "_");
	PlayerTextDrawFont(playerid, HBEBGFOOD[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEBGFOOD[playerid], 0.600000, 1.650002);
	PlayerTextDrawTextSize(playerid, HBEBGFOOD[playerid], 298.500000, 82.500000);
	PlayerTextDrawSetOutline(playerid, HBEBGFOOD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEBGFOOD[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEBGFOOD[playerid], 2);
	PlayerTextDrawColor(playerid, HBEBGFOOD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEBGFOOD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEBGFOOD[playerid], 135);
	PlayerTextDrawUseBox(playerid, HBEBGFOOD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEBGFOOD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEBGFOOD[playerid], 0);

	HBEBGDRINK[playerid] = CreatePlayerTextDraw(playerid, 594.000000, 424.000000, "_");
	PlayerTextDrawFont(playerid, HBEBGDRINK[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEBGDRINK[playerid], 0.600000, 1.650002);
	PlayerTextDrawTextSize(playerid, HBEBGDRINK[playerid], 298.500000, 82.500000);
	PlayerTextDrawSetOutline(playerid, HBEBGDRINK[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEBGDRINK[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEBGDRINK[playerid], 2);
	PlayerTextDrawColor(playerid, HBEBGDRINK[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEBGDRINK[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEBGDRINK[playerid], 135);
	PlayerTextDrawUseBox(playerid, HBEBGDRINK[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEBGDRINK[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEBGDRINK[playerid], 0);

	HBEBGFOOD1[playerid] = CreatePlayerTextDraw(playerid, 535.000000, 395.000000, "_");
	PlayerTextDrawFont(playerid, HBEBGFOOD1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEBGFOOD1[playerid], 0.600000, 1.650002);
	PlayerTextDrawTextSize(playerid, HBEBGFOOD1[playerid], 298.500000, 19.500000);
	PlayerTextDrawSetOutline(playerid, HBEBGFOOD1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEBGFOOD1[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEBGFOOD1[playerid], 2);
	PlayerTextDrawColor(playerid, HBEBGFOOD1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEBGFOOD1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEBGFOOD1[playerid], 135);
	PlayerTextDrawUseBox(playerid, HBEBGFOOD1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEBGFOOD1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEBGFOOD1[playerid], 0);

	HBEBGDRINK1[playerid] = CreatePlayerTextDraw(playerid, 535.000000, 424.000000, "_");
	PlayerTextDrawFont(playerid, HBEBGDRINK1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEBGDRINK1[playerid], 0.600000, 1.650002);
	PlayerTextDrawTextSize(playerid, HBEBGDRINK1[playerid], 298.500000, 19.500000);
	PlayerTextDrawSetOutline(playerid, HBEBGDRINK1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEBGDRINK1[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEBGDRINK1[playerid], 2);
	PlayerTextDrawColor(playerid, HBEBGDRINK1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEBGDRINK1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEBGDRINK1[playerid], 135);
	PlayerTextDrawUseBox(playerid, HBEBGDRINK1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEBGDRINK1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEBGDRINK1[playerid], 0);

	HBEBGMONEY[playerid] = CreatePlayerTextDraw(playerid, 594.000000, 374.000000, "_");
	PlayerTextDrawFont(playerid, HBEBGMONEY[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEBGMONEY[playerid], 0.600000, 0.850003);
	PlayerTextDrawTextSize(playerid, HBEBGMONEY[playerid], 298.500000, 82.500000);
	PlayerTextDrawSetOutline(playerid, HBEBGMONEY[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEBGMONEY[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEBGMONEY[playerid], 2);
	PlayerTextDrawColor(playerid, HBEBGMONEY[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEBGMONEY[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEBGMONEY[playerid], 135);
	PlayerTextDrawUseBox(playerid, HBEBGMONEY[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEBGMONEY[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEBGMONEY[playerid], 0);

	HBEBGMONEY1[playerid] = CreatePlayerTextDraw(playerid, 535.000000, 374.000000, "_");
	PlayerTextDrawFont(playerid, HBEBGMONEY1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEBGMONEY1[playerid], 0.600000, 0.850003);
	PlayerTextDrawTextSize(playerid, HBEBGMONEY1[playerid], 300.500000, 20.000000);
	PlayerTextDrawSetOutline(playerid, HBEBGMONEY1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEBGMONEY1[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEBGMONEY1[playerid], 2);
	PlayerTextDrawColor(playerid, HBEBGMONEY1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEBGMONEY1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEBGMONEY1[playerid], 135);
	PlayerTextDrawUseBox(playerid, HBEBGMONEY1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEBGMONEY1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEBGMONEY1[playerid], 0);

	HBEMONEY[playerid] = CreatePlayerTextDraw(playerid, 529.000000, 373.000000, "HUD:radar_cash");
	PlayerTextDrawFont(playerid, HBEMONEY[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBEMONEY[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEMONEY[playerid], 11.000000, 12.500000);
	PlayerTextDrawSetOutline(playerid, HBEMONEY[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEMONEY[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEMONEY[playerid], 1);
	PlayerTextDrawColor(playerid, HBEMONEY[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEMONEY[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEMONEY[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBEMONEY[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEMONEY[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEMONEY[playerid], 0);

	HBEFOOD[playerid] = CreatePlayerTextDraw(playerid, 528.000000, 395.000000, "HUD:radar_chicken");
	PlayerTextDrawFont(playerid, HBEFOOD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBEFOOD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEFOOD[playerid], 16.000000, 16.000000);
	PlayerTextDrawSetOutline(playerid, HBEFOOD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEFOOD[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEFOOD[playerid], 1);
	PlayerTextDrawColor(playerid, HBEFOOD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEFOOD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEFOOD[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBEFOOD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEFOOD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEFOOD[playerid], 0);

	HBEDRINK[playerid] = CreatePlayerTextDraw(playerid, 528.000000, 424.000000, "HUD:radar_diner");
	PlayerTextDrawFont(playerid, HBEDRINK[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBEDRINK[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEDRINK[playerid], 16.000000, 16.000000);
	PlayerTextDrawSetOutline(playerid, HBEDRINK[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEDRINK[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEDRINK[playerid], 1);
	PlayerTextDrawColor(playerid, HBEDRINK[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEDRINK[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEDRINK[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBEDRINK[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEDRINK[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEDRINK[playerid], 0);

	HBEMONEYTEXT[playerid] = CreatePlayerTextDraw(playerid, 556.000000, 372.000000, "000,000.00");
	PlayerTextDrawFont(playerid, HBEMONEYTEXT[playerid], 3);
	PlayerTextDrawLetterSize(playerid, HBEMONEYTEXT[playerid], 0.383332, 1.499999);
	PlayerTextDrawTextSize(playerid, HBEMONEYTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HBEMONEYTEXT[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEMONEYTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEMONEYTEXT[playerid], 1);
	PlayerTextDrawColor(playerid, HBEMONEYTEXT[playerid], 9109759);
	PlayerTextDrawBackgroundColor(playerid, HBEMONEYTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEMONEYTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBEMONEYTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, HBEMONEYTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEMONEYTEXT[playerid], 0);

	HBEFOODBAR[playerid] = CreatePlayerProgressBar(playerid, 559.000000, 399.000000, 73.000000, 6.000000, -65281, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, HBEFOODBAR[playerid], 50.000000);

	HBEDRINKBAR[playerid] = CreatePlayerProgressBar(playerid, 559.000000, 429.000000, 73.000000, 6.000000, -65281, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, HBEDRINKBAR[playerid], 50.000000);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, HBEBGFOOD[playerid]);
	PlayerTextDrawDestroy(playerid, HBEBGDRINK[playerid]);
	PlayerTextDrawDestroy(playerid, HBEBGFOOD1[playerid]);
	PlayerTextDrawDestroy(playerid, HBEBGDRINK1[playerid]);
	PlayerTextDrawDestroy(playerid, HBEBGMONEY[playerid]);
	PlayerTextDrawDestroy(playerid, HBEBGMONEY1[playerid]);
	PlayerTextDrawDestroy(playerid, HBEMONEY[playerid]);
	PlayerTextDrawDestroy(playerid, HBEFOOD[playerid]);
	PlayerTextDrawDestroy(playerid, HBEDRINK[playerid]);
	PlayerTextDrawDestroy(playerid, HBEMONEYTEXT[playerid]);
	DestroyPlayerProgressBar(playerid, HBEFOODBAR[playerid]);
	DestroyPlayerProgressBar(playerid, HBEDRINKBAR[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, HBEBGFOOD[playerid]);
		PlayerTextDrawShow(playerid, HBEBGDRINK[playerid]);
		PlayerTextDrawShow(playerid, HBEBGFOOD1[playerid]);
		PlayerTextDrawShow(playerid, HBEBGDRINK1[playerid]);
		PlayerTextDrawShow(playerid, HBEBGMONEY[playerid]);
		PlayerTextDrawShow(playerid, HBEBGMONEY1[playerid]);
		PlayerTextDrawShow(playerid, HBEMONEY[playerid]);
		PlayerTextDrawShow(playerid, HBEFOOD[playerid]);
		PlayerTextDrawShow(playerid, HBEDRINK[playerid]);
		PlayerTextDrawShow(playerid, HBEMONEYTEXT[playerid]);
		ShowPlayerProgressBar(playerid, HBEFOODBAR[playerid]);
		ShowPlayerProgressBar(playerid, HBEDRINKBAR[playerid]);
		return 1;
	}
	return 0;
}
